version: "3"

services:
  app:
    build:
      contect:
    ports:
      - "80:80"
    voiumes:
      -./app:/code/app
    depends_on:
      -db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    voiumes:
      -postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: